services:
  web:
    image: samuelogboye/nearbytixweb:latest
    container_name: nearbytix_web
    env_file:
      - .env
    ports:
      - "${PORT:-5173}:5173"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
